# Generated by Django 3.2.6 on 2021-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210817_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('бег', 'Run'), ('ходьба', 'Walk'), ('велосипед', 'Bicycle')], default='null', max_length=25),
        ),
    ]
