# Generated by Django 3.2.6 on 2021-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210817_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Бег', 'Run'), ('Ходьба', 'Walk'), ('Велосипед', 'Bicycle')], default='null', max_length=25),
        ),
    ]
